# Generated by Django 5.2.8 on 2026-01-09 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMarblesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased_name', models.CharField(max_length=200, verbose_name='ชื่อผู้วายชนม์ (บนป้าย)')),
                ('deceased_photo', models.ImageField(upload_to='customer_marbles_uploads/%Y/%m/', verbose_name='รูปถ่าย')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='วัน/เดือน/ปีเกิด')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='วัน/เดือน/ปีมรณะ')),
                ('stone_style', models.CharField(choices=[('black_granite', 'หินแกรนิตดำ')], max_length=50, verbose_name='รูปแบบหิน')),
                ('size', models.CharField(choices=[('15x20', '15x20 ซม. (1,000 บาท)'), ('14x29', '14x29 ซม. (1,700 บาท)')], default='15x20', max_length=20, verbose_name='ขนาด')),
                ('note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุเพิ่มเติม')),
                ('payment_method', models.CharField(choices=[('transfer', 'โอนเงินผ่านธนาคาร')], default='transfer', max_length=20, verbose_name='วิธีชำระเงิน')),
                ('shipping_method', models.CharField(choices=[('pickup', 'รับเองที่ร้าน (ฟรี)'), ('standard', 'ขนส่งธรรมดา (50 บาท)'), ('express', 'ขนส่งด่วน (100 บาท)')], default='pickup', max_length=20, verbose_name='วิธีจัดส่ง')),
                ('PAYMENT_SLIP', models.ImageField(blank=True, null=True, upload_to='payment_slips_order_marbles/%Y/%m/', verbose_name='สลิปโอนเงิน')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='ราคาป้าย (บาท)')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคาสุทธิ (รวมส่ง)')),
                ('status', models.CharField(choices=[('pending', 'รอชำระเงิน'), ('processing', 'กำลังผลิต/เตรียมพัสดุ'), ('shipped', 'จัดส่งแล้ว'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สั่ง')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้สั่งทำ (User ID)')),
            ],
            options={
                'verbose_name': 'รายการสั่งทำป้าย',
                'verbose_name_plural': 'รายการสั่งทำป้ายทั้งหมด',
            },
        ),
    ]
