# Generated by Django 5.2.8 on 2026-01-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framings', '0006_alter_customframeorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customframeorder',
            name='payment_slip',
            field=models.ImageField(blank=True, null=True, upload_to='payment_slips_order_framings/%Y/%m/', verbose_name='สลิปโอนเงิน'),
        ),
        migrations.AlterField(
            model_name='customframeorder',
            name='size_option',
            field=models.CharField(choices=[('8x10', '8 x 10 นิ้ว'), ('10x12', '10 x 12 นิ้ว'), ('16x20', '16 x 20 นิ้ว'), ('20x24', '20 x 24 นิ้ว')], max_length=10, verbose_name='ขนาด'),
        ),
        migrations.AlterField(
            model_name='customframeorder',
            name='uploaded_image',
            field=models.ImageField(upload_to='customer_framings_uploads/%Y/%m/', verbose_name='รูปจากลูกค้า'),
        ),
    ]
